name: lunofono_bundle_example
description: Demonstrate how to use the lunofono bundle library.

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  lunofono_bundle:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
